import argparse
from pathlib import Path
THIS_DIR = Path(__file__).resolve().parent

def create_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--device', default='cuda', type=str)
    parser.add_argument('--gpu', default=0, type=int)
    parser.add_argument('--seed', default=42, type=int)
    parser.add_argument('--model_name', default='MA-IAM4VP', type=str)
    parser.add_argument('--in_shape', default=[10, 1, 384, 384], type=int, nargs='*')
    parser.add_argument('--out_T', default=12, type=int)
    parser.add_argument('--split_ratio', default=[0.8, 0.1, 0.1], type=float, nargs=3)
    parser.add_argument('--batch_size', default=1, type=int)
    parser.add_argument('--val_batch_size', default=1, type=int)
    parser.add_argument('--max_train_batches', default=0, type=int)
    parser.add_argument('--max_val_batches', default=0, type=int)
    parser.add_argument('--max_test_batches', default=0, type=int)
    parser.add_argument('--checkpoint_dir', default=str(THIS_DIR / 'checkpoints'), type=str)
    parser.add_argument('--hid_S', default=64, type=int)
    parser.add_argument('--N_S', default=4, type=int)
    parser.add_argument('--N_T', default=8, type=int)
    parser.add_argument('--epochs', default=150, type=int)
    parser.add_argument('--optimizer', default='AdamW', type=str)
    parser.add_argument('--lr', default=0.0001, type=float)
    parser.add_argument('--lr_min', default=1e-06, type=float)
    parser.add_argument('--weight_decay', default=1e-05, type=float)
    parser.add_argument('--scheduler', default='CosineAnnealingLR', type=str)
    parser.add_argument('--accum_steps', default=8, type=int)
    parser.add_argument('--early_stop_metric', default='ssim', type=str)
    parser.add_argument('--early_stop_start_epoch', default=30, type=int)
    parser.add_argument('--early_stop_patience', default=12, type=int)
    parser.add_argument('--early_stop_min_delta', default=0.0001, type=float)
    parser.add_argument('--weak_echo_thr', default=0.15, type=float)
    parser.add_argument('--adaptive_mask_prob', default=0.2, type=float)
    parser.add_argument('--temporal_attention_kernel', default=7, type=int)
    parser.add_argument('--strong_echo_thr', default=0.3, type=float)
    parser.add_argument('--strong_echo_cap', default=2.0, type=float)
    parser.add_argument('--binary_metric_threshold', default=0.3, type=float)
    parser.add_argument('--refine_mid_channels', default=32, type=int)
    parser.add_argument('--refiner_delta_scale', default=0.3, type=float)
    parser.add_argument('--teacher_forcing_start', default=1.0, type=float)
    parser.add_argument('--teacher_forcing_end', default=0.5, type=float)
    parser.add_argument('--teacher_forcing_decay_epochs', default=30, type=int)
    return parser
